import { Plus_Jakarta_Sans, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Hero from "./_components/Hero";
import { Providers as ThemeProvider } from "./_context/ThemeContext";
import AnimatedCursor from "react-animated-cursor";

// Initialize Plus Jakarta Sans with the required subset
const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
});

// Initialize DM Sans with the required subset
const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jakarta.className} ${dmSans.className} dark:bg-gray-900 bg-gray-50 overflow-x-hidden`}
      >
        <AnimatedCursor
          innerSize={12}
          outerSize={48}
          color="2, 132, 233" // White color for cursor
          outerAlpha={0.5}
          innerScale={0.3}
          outerScale={2}
          style={{
            mixBlendMode: "difference", // Apply difference blend mode
          }}
          clickables={[
            "a",
            'input[type="text"]',
            'input[type="email"]',
            'input[type="number"]',
            'input[type="submit"]',
            'input[type="image"]',
            "label[for]",
            "select",
            "textarea",
            "button",
            ".link",
          ]}
        />
        <ThemeProvider>
          <>{children}</>
        </ThemeProvider>
      </body>
    </html>
  );
}
